### ISSUE TITLE
prevent users from using the same display names

### ISSUE THREAD

**Issue by andrewjs18** [Sama34/Display-Usernames-Nicks-Plugin#5]
just as we prevent users from using the same usernames, we should also prevent them from using the same display names as well.

**Comment by Sama34** [comment]
I just tried to change my display name to a repeated one and it didn't allow me to.

**Comment by andrewjs18** [comment]
did it error out?

**Comment by andrewjs18** [comment]
ok, it does look like it runs checks:

![2019-02-04 16_04_28](https://user-images.githubusercontent.com/2748980/52237069-94e8c900-2896-11e9-9a19-714da1cb9073.png)
